version: '3.0'
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    volumes:
    - mongo_data:/data/db
    ports:
    - 127.0.0.1:27017:27017

  misty:
    build: ./Misty
    container_name: "misty"
    depends_on:
      - mongo
    restart: on-failure:15

volumes:
  mongo_data: